---
title: "flowPloidy Data"
author: "Tyler Smith"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{flowPloidy Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This package contains a collection of flow cytometry data files. They are in the LMD format, as generated by a Beckman-Coulter Gallios flow cytometer. 

The samples are plant leaf tissues from a variety of species. Each sample is co-chopped with a standard (e.g., soybean or tomato) with known GC values. Consequently, in successful assays you'll see the G1 peak for the sample and another G1 peak for the standard. Depending on the samples, you may also see a G2 peak for one or both of these as well, at approximately twice the intensity.

The files include a mix of low- and high-quality data, to provide useful examples for how the flowPloidy package deals with good and bad situations. 

This package provides a single variable, useful as a convenience for accessing the files from an R session: `flowPloidyFiles`. This is a list of all the data files, which you can pass to functions such as `flowPloidy::histBatch(flowPloidyFiles, ...)` (which will read in all the files in the vector), or `flowCore::read.FCS(flowPloidyFiles[1], ...)` (to read in the first file in the vector).

For further information, see the `flowPloidy` package.
